The @{u}..avar/test-lib-various-2 patch series

diff --git a/avar/test-lib-various-2/v2-0000-cover-letter.patch b/avar/test-lib-various-2/v2-0000-cover-letter.patch
--- a/avar/test-lib-various-2/v2-0000-cover-letter.patch
+++ b/avar/test-lib-various-2/v2-0000-cover-letter.patch
@@ -1,9 +1,9 @@
 From 85b33dfd9631c53c0b459817d19261090b2798d7 Mon Sep 17 00:00:00 2001
-Message-Id: <cover-00.15-00000000000-20210417T092232Z-avarab@gmail.com>
+Message-Id: <cover-00.15-00000000000-20210417T092251Z-avarab@gmail.com>
 In-Reply-To: <cover-00.16-00000000000-20210412T110456Z-avarab@gmail.com>
 References: <cover-00.16-00000000000-20210412T110456Z-avarab@gmail.com>
 From: Ævar Arnfjörð Bjarmason <avarab@gmail.com>
-Date: Sat, 17 Apr 2021 11:22:32 +0200
+Date: Sat, 17 Apr 2021 11:22:51 +0200
 Subject: [PATCH v2 00/15] *** SUBJECT HERE ***
 MIME-Version: 1.0
 Content-Type: text/plain; charset=UTF-8
@@ -46,21 +46,343 @@ Content-Transfer-Encoding: 8bit
  15 files changed, 115 insertions(+), 160 deletions(-)
 
 Range-diff against v1:
+ 1:  8e4b4a2a216 <  -:  ----------- check-non-portable-shell: complain about "test" a/-o instead of &&/||
  -:  ----------- >  1:  a8b483bc771 check-non-portable-shell: check for "test <cond> -a/-o <cond>"
- -:  ----------- >  2:  39759d00adf test-lib: bring $remove_trash out of retirement
- -:  ----------- >  3:  d669ce31961 test-lib tests: remove dead GIT_TEST_FRAMEWORK_SELFTEST variable
- -:  ----------- >  4:  9313d35bf86 test-lib-functions: reword "test_commit --append" docs
- -:  ----------- >  5:  c916d648e49 test-lib-functions: document test_commit --no-tag
- -:  ----------- >  6:  9b6bf65ce1c test-lib functions: add an --annotated option to "test_commit"
- -:  ----------- >  7:  683b3ba3dd9 describe tests: convert setup to use test_commit
- -:  ----------- >  8:  dc0a863db72 test-lib functions: add --printf option to test_commit
- -:  ----------- >  9:  90bf55d2d42 submodule tests: use symbolic-ref --short to discover branch name
- -:  ----------- > 10:  e0a1e2fd529 test-lib: reformat argument list in test_create_repo()
- -:  ----------- > 11:  cedf5d383b0 test-lib: do not show advice about init.defaultBranch under --verbose
- -:  ----------- > 12:  241a392b8e4 test-lib: split up and deprecate test_create_repo()
- -:  ----------- > 13:  00c6175a1db test-lib-functions: normalize test_path_is_missing() debugging
- -:  ----------- > 14:  547ebd6255d Revert and amend "test-lib-functions: assert correct parameter count"
- -:  ----------- > 15:  85b33dfd963 test-lib-functions: remove last two parameter count assertions
+ 2:  44223ae777e !  2:  39759d00adf test-lib: bring $remove_trash out of retirement
+    @@ Commit message
+         test-lib: bring $remove_trash out of retirement
+     
+         There's no point in creating a repository or directory only to decide
+    -    right afterwards that we're skipping all the tests.
+    +    right afterwards that we're skipping all the tests. We can save
+    +    ourselves the redundant "git init" or "mkdir" and "rm -rf" in this
+    +    case.
+    +
+    +    We carry around the "$remove_trash" variable because if the directory
+    +    is unexpectedly gone at test_done time we'll hit the error about it
+    +    being unexpectedly gone added in df4c0d1a792 (test-lib: abort when
+    +    can't remove trash directory, 2017-04-20).
+     
+         So let's partially revert 06478dab4c (test-lib: retire $remove_trash
+         variable, 2017-04-23) and move the decision about whether to skip all
+ 3:  3d04553d710 =  3:  d669ce31961 test-lib tests: remove dead GIT_TEST_FRAMEWORK_SELFTEST variable
+ 4:  4ecce153b99 =  4:  9313d35bf86 test-lib-functions: reword "test_commit --append" docs
+ 5:  6df03776940 !  5:  c916d648e49 test-lib-functions: document test_commit --no-tag
+    @@ t/test-lib-functions.sh: debug () {
+      #   --author <author>
+      #	Invoke "git commit" with --author <author>
+     +#   --no-tag
+    -+#	Do not tag the resulting commit, if supplied giving the
+    -+#	optional "<tag>" argument is an error.
+    ++#	Do not tag the resulting commit
+      #
+      # This will commit a file with the given contents and the given commit
+      # message, and tag the resulting commit with the given tag name.
+ 6:  8d43fdd5865 !  6:  9b6bf65ce1c test-lib functions: add an --annotated-tag option to "test_commit"
+    @@ Metadata
+     Author: Ævar Arnfjörð Bjarmason <avarab@gmail.com>
+     
+      ## Commit message ##
+    -    test-lib functions: add an --annotated-tag option to "test_commit"
+    +    test-lib functions: add an --annotated option to "test_commit"
+     
+    -    Add an --annotated-tag option to test_commit. The tag will share the
+    -    same message as the commit, and we'll call test_tick before creating
+    -    it (unless --notick) is provided.
+    +    Add an --annotated option to test_commit to create annotated tags. The
+    +    tag will share the same message as the commit, and we'll call
+    +    test_tick before creating it (unless --notick) is provided.
+     
+         There's quite a few tests that could be simplified with this
+         construct. I've picked one to convert in this change as a
+    @@ t/t1403-show-ref.sh: export GIT_TEST_DEFAULT_INITIAL_BRANCH_NAME
+     
+      ## t/test-lib-functions.sh ##
+     @@ t/test-lib-functions.sh: debug () {
+    + #	Invoke "git commit" with --author <author>
+      #   --no-tag
+    - #	Do not tag the resulting commit, if supplied giving the
+    - #	optional "<tag>" argument is an error.
+    + #	Do not tag the resulting commit
+     +#   --annotate
+     +#	Create an annotated tag with "--annotate -m <message>". Calls
+    -+#	test_tick between making the commit and tag unless --notick is
+    -+#	given.
+    ++#	test_tick between making the commit and tag, unless --notick
+    ++#	is given.
+      #
+      # This will commit a file with the given contents and the given commit
+      # message, and tag the resulting commit with the given tag name.
+    @@ t/test-lib-functions.sh: test_commit () {
+     -	fi
+     +		;;
+     +	annotate)
+    -+		if test "$tag$notick" = "annotate"
+    ++		if test -z "$notick"
+     +		then
+     +			test_tick
+     +		fi &&
+ 7:  ec4809e7466 =  7:  683b3ba3dd9 describe tests: convert setup to use test_commit
+ 8:  352eeff41c9 =  8:  dc0a863db72 test-lib functions: add --printf option to test_commit
+ 9:  e7432294215 =  9:  90bf55d2d42 submodule tests: use symbolic-ref --short to discover branch name
+10:  634038c3a8d = 10:  e0a1e2fd529 test-lib: reformat argument list in test_create_repo()
+11:  cdbff4df362 = 11:  cedf5d383b0 test-lib: do not show advice about init.defaultBranch under --verbose
+12:  424caad189f ! 12:  241a392b8e4 test-lib: modernize test_create_repo() function
+    @@ Metadata
+     Author: Ævar Arnfjörð Bjarmason <avarab@gmail.com>
+     
+      ## Commit message ##
+    -    test-lib: modernize test_create_repo() function
+    +    test-lib: split up and deprecate test_create_repo()
+     
+    -    Remove redundant "mkdir -p", argument number checking', test
+    -    environment sanity checking, and disabling of hooks from
+    -    test_create_repo(). As we'll see below these were all either redundant
+    -    to other test other framework code, or to changes in git itself.
+    +    Remove various redundant or obsolete code from the test_create_repo()
+    +    function, and split up its use in test-lib.sh from what tests need
+    +    from it, leaving us with a pass-through wrapper for "git init" in
+    +    test-lib-functions.sh
+     
+    -    Respectively:
+    +    Reasons for why we can remove various code from test_create_repo():
+     
+          1. "mkdir -p" isn't needed because "git init" itself will create
+             leading directories if needed.
+     
+    -     2. We don't need to check the number of arguments anymore, instead
+    -        we'll feed "git init" with "$@". It will die if given too many
+    -        arguments.
+    +     2. Since we're now a simple wrapper for "git init" we don't need to
+    +        check that we have only one argument. If someone wants to run
+    +        "test_create_repo --bare x" that's OK.
+     
+          3. We won't ever hit that "Cannot setup test environment"
+             error.
+    @@ Commit message
+          5. Since we don't need to move the .git/hooks directory we don't need
+             the subshell here either.
+     
+    +        That wasn't really needed for the .git/hooks either, but was being
+    +        done for the convenience of not having to quote the path to the
+    +        repository as we moved the hooks.
+    +
+    +     6. We can drop the --template argument and instead rely on the
+    +        GIT_TEMPLATE_DIR set to the same path earlier in test-lib.sh. See
+    +        8683a45d669 (Introduce GIT_TEMPLATE_DIR, 2006-12-19)
+    +
+    +     7. We only needed that ">&3 2>&4" redirection when invoked from
+    +        test-lib.sh, and the same goes for needing the full path to "git".
+    +
+    +        Let's move that special behavior into test-lib.sh itself.
+    +
+         In the end it turns out that all we needed was a plain "git init"
+    -    invocation with a custom --template directory.
+    +    invocation. I'm keeping the split of "git" "init" and its arguments
+    +    over multiple lines in anticipation of a future series of mine where
+    +    we'll add a "--quiet" (and print out a custom debug message instead).
+     
+         Signed-off-by: Ævar Arnfjörð Bjarmason <avarab@gmail.com>
+     
+    @@ t/t5409-colorize-remote-messages.sh: test_description='remote messages are color
+     
+      ## t/test-lib-functions.sh ##
+     @@ t/test-lib-functions.sh: test_atexit () {
+    - # Most tests can use the created repository, but some may need to create more.
+    + 		} && (exit \"\$eval_ret\"); eval_ret=\$?; $test_atexit_cleanup"
+    + }
+    + 
+    +-# Most tests can use the created repository, but some may need to create more.
+    ++# Deprecated wrapper for "git init"
+      # Usage: test_create_repo <directory>
+      test_create_repo () {
+     -	test "$#" = 1 ||
+    @@ t/test-lib-functions.sh: test_atexit () {
+     -		error "cannot run git init -- have you built things yet?"
+     -		mv .git/hooks .git/hooks-disabled
+     -	) || exit
+    -+	"${GIT_TEST_INSTALLED:-$GIT_EXEC_PATH}/git$X" \
+    ++	git \
+     +		init \
+    -+		"--template=$GIT_BUILD_DIR/templates/blt/" "$@" >&3 2>&4
+    ++		"$@"
+      }
+      
+      # This function helps on symlink challenged file systems when it is not
+    +
+    + ## t/test-lib.sh ##
+    +@@ t/test-lib.sh: rm -fr "$TRASH_DIRECTORY" || {
+    + remove_trash=t
+    + if test -z "$TEST_NO_CREATE_REPO"
+    + then
+    +-	test_create_repo "$TRASH_DIRECTORY"
+    ++	"${GIT_TEST_INSTALLED:-$GIT_BUILD_DIR}/git$X" \
+    ++		init \
+    ++		"$TRASH_DIRECTORY" >&3 2>&4 ||
+    ++	error "cannot run git init"
+    + else
+    + 	mkdir -p "$TRASH_DIRECTORY"
+    + fi
+13:  0813aa8e34e = 13:  00c6175a1db test-lib-functions: normalize test_path_is_missing() debugging
+14:  b6e9d971b40 <  -:  ----------- test-lib-functions: use "return 1" instead of "false"
+15:  0cd511206c4 ! 14:  547ebd6255d Revert and amend "test-lib-functions: assert correct parameter count"
+    @@ Commit message
+         assert correct parameter count, 2021-02-12) in order to improve the -x
+         output.
+     
+    -    When I added these BUG assertions in e7884b353b7 I missed that this
+    -    made the -x output much more verbose.
+    +    The goal here is to get rid of the verbosity of having e.g. a "test 2
+    +    -ne 2" line for every "test_cmp". We use "$@" as an argument to "test"
+    +    to intentionally feed the "test" operator too many arguments if the
+    +    functions are called with too many arguments, thus piggy-backing on it
+    +    to check the number of arguments we get.
+     
+    -    E.g. for each test_cmp invocation we'd now emit:
+    +    Before this for each test_cmp invocation we'd emit:
+     
+             + test_cmp expect actual
+             + test 2 -ne 2
+             + eval diff -u "$@"
+             + diff -u expect actual
+     
+    -    That "test 2 -ne 2" line is new in e7884b353b7. As noted in
+    +    That "test 2 -ne 2" line is new in my e7884b353b7. As noted in
+         45a2686441b (test-lib-functions: remove bug-inducing "diagnostics"
+         helper param, 2021-02-12) we had buggy invocations of some of these
+         functions with too many parameters.
+     
+    -    Let's instead use "$@" instead of "$1" to achieve the same ends with
+    -    no extra -x output verbosity. The "test" operator will die with an
+    -    error if given more than one argument in these contexts, so using "$@"
+    -    achieves the same goal.
+    +    Now we'll get just:
+     
+    -    The same goes for "cmp" and "diff -u" (which we typically use for
+    -    test_cmp).
+    +        + test_cmp expect actual
+    +        + eval diff -u "$@"
+    +        + diff -u expect actual
+    +
+    +    This does not to the "right" thing in cases like:
+    +
+    +        test_path_is_file x -a y
+    +
+    +    Which will now turn into:
+    +
+    +        test -f x -a y
+    +
+    +    I consider that to be OK given the trade-off that any extra checking
+    +    would produce more verbose trace output. As shown in 45a2686441b we
+    +    had issues with these functions being invoked with multiple
+    +    parameters (e.g. a glob) by accident, we don't need to be paranoid in
+    +    guarding against hostile misuse from our own test suite.
+    +
+    +    While I'm at it change a few functions that relied on a "false" being
+    +    the last statement in the function to use an explicit "return 1" like
+    +    the other functions in this file.
+     
+         Signed-off-by: Ævar Arnfjörð Bjarmason <avarab@gmail.com>
+     
+    @@ t/test-lib-functions.sh: test_external_without_stderr () {
+     +	if ! test -f "$@"
+      	then
+     -		echo "File $1 doesn't exist"
+    -+		echo "File $@ doesn't exist"
+    - 		return 1
+    +-		false
+    ++		echo "File $* doesn't exist"
+    ++		return 1
+      	fi
+      }
+      
+    @@ t/test-lib-functions.sh: test_external_without_stderr () {
+     +	if ! test -d "$@"
+      	then
+     -		echo "Directory $1 doesn't exist"
+    -+		echo "Directory $@ doesn't exist"
+    - 		return 1
+    +-		false
+    ++		echo "Directory $* doesn't exist"
+    ++		return 1
+      	fi
+      }
+      
+    @@ t/test-lib-functions.sh: test_external_without_stderr () {
+     +	if ! test -e "$@"
+      	then
+     -		echo "Path $1 doesn't exist"
+    -+		echo "Path $@ doesn't exist"
+    - 		return 1
+    +-		false
+    ++		echo "Path $* doesn't exist"
+    ++		return 1
+      	fi
+      }
+      
+    @@ t/test-lib-functions.sh: test_external_without_stderr () {
+     +	if test -n "$(ls -a1 "$@" | egrep -v '^\.\.?$')"
+      	then
+     -		echo "Directory '$1' is not empty, it contains:"
+    -+		echo "Directory '$@' is not empty, it contains:"
+    ++		echo "Directory '$*' is not empty, it contains:"
+      		ls -la "$1"
+      		return 1
+      	fi
+    @@ t/test-lib-functions.sh: test_dir_is_empty () {
+     +	if ! test -s "$@"
+      	then
+     -		echo "'$1' is not a non-empty file."
+    -+		echo "'$@' is not a non-empty file."
+    - 		return 1
+    +-		false
+    ++		echo "'$*' is not a non-empty file."
+    ++		return 1
+      	fi
+      }
+      
+    @@ t/test-lib-functions.sh: test_dir_is_empty () {
+     -	if test -e "$1"
+     +	if test -e "$@"
+      	then
+    - 		echo "Path $1 exists!"
+    +-		echo "Path $1 exists!"
+    ++		echo "Path $* exists!"
+      		false
+    + 	fi
+    + }
+     @@ t/test-lib-functions.sh: test_expect_code () {
+      # - not all diff versions understand "-u"
+      
+    @@ t/test-lib-functions.sh: verbose () {
+      	then
+     -		echo "'$1' is not empty, it contains:"
+     -		cat "$1"
+    -+		echo "'$@' is not empty, it contains:"
+    ++		echo "'$*' is not empty, it contains:"
+     +		cat "$@"
+      		return 1
+      	fi
+16:  b4a018a63f3 ! 15:  85b33dfd963 test-lib-functions: remove last two parameter count assertions
+    @@ Metadata
+      ## Commit message ##
+         test-lib-functions: remove last two parameter count assertions
+     
+    -    Remove a couple of parameter count assertions where we'll now silently
+    -    do the wrong thing if given too many parameters, unlike the "$@" cases
+    -    in the preceding commit where "test" etc. handle the check for usi.
+    +    Remove a couple of parameter count assertions where, unlike the
+    +    preceding commit's migration to 'test -$x "$@"', we'll now silently do
+    +    the "wrong" thing if given too many parameters. The benefit is less
+    +    verbose trace output, as noted in the preceding commit.
+     
+         In the case of "test_file_size", the "test-tool" we're invoking is
+         happy to accept N parameters (it'll print out all N sizes). Let's just
+    -    use "$@" in that case anyway, there's only a few callers, and
+    +    use "$@" in that case anyway. There's only a few callers, and
+         eventually those should probably be moved to use the test-tool
+         directly.
+     
 -- 
 2.31.1.687.g1d87aeed692
 
