bump cl

diff --git a/gettext-poison-refactor-2/0001-i18n-make-GETTEXT_POISON-a-runtime-option.patch b/gettext-poison-refactor-2/0001-i18n-make-GETTEXT_POISON-a-runtime-option.patch
--- a/gettext-poison-refactor-2/0001-i18n-make-GETTEXT_POISON-a-runtime-option.patch
+++ b/gettext-poison-refactor-2/0001-i18n-make-GETTEXT_POISON-a-runtime-option.patch
@@ -93,6 +93,407 @@ more discussion.
 
 Signed-off-by: Ævar Arnfjörð Bjarmason <avarab@gmail.com>
 ---
+
+On Wed, Oct 24 2018, Junio C Hamano wrote:
+
+> Ævar Arnfjörð Bjarmason  <avarab@gmail.com> writes:
+>
+>> Notes on the implementation:
+>>
+>>  * The only reason we need a new "git-sh-i18n--helper" and the
+>>    corresponding "test-tool gettext-poison" is to expose
+>>    git_env_bool() to shellscripts, since git-sh-i18n and friends need
+>>    to inspect the $GIT_TEST_GETTEXT_POISON variable.
+>>
+>>    We only call these if $GIT_TEST_GETTEXT_POISON is set, or in the
+>>    test suite, and this code can go away for non-test code once the
+>>    last i18n-using shellscript is rewritten in C.
+>
+> Makes me wonder if we want to teach "git config" a new "--env-bool"
+> option that can be used by third-party scripts.  Or would it be just
+> the matter of writing
+>
+> 	git config --default=false --type=bool "$GIT_WHATEVER_ENV"
+>
+> in these third-party scripts and we do not need to add such a thing?
+
+As Jeff notes in a follow-up reply git-config can't quite do this
+yet. So in lieu of implementing that I have a more minimal helper,
+which could be migrated to something like the --get-env mode Jeff is
+talking about if we add that.
+
+>>  * The reason for not doing:
+>>
+>>        test_lazy_prereq GETTEXT_POISON 'test-tool gettext-poison'
+>>        test_lazy_prereq C_LOCALE_OUTPUT '! test-tool gettext-poison'
+>>
+>>    In test-lib.sh is because there's some interpolation problem with
+>>    that syntax which makes t6040-tracking-info.sh fail. Hence using
+>>    the simpler test_set_prereq.
+>
+> s/In/in/, as you haven't finished the sentence yet.  But more
+> importantly, what is this "some interpolation problem"?  Are you
+> saying that test_lazy_prereq implementation is somehow broken and
+> cannot take certain strings?  If so, perhaps we want to fix that,
+> and people other than you can help to do so, once you let them know
+> what the problem is.
+
+I haven't fixed (don't know what the fix is) this issue, but the new
+version elaborates on what the error is.
+
+>> See also
+>> https://public-inbox.org/git/871s8gd32p.fsf@evledraar.gmail.com/ for
+>> more discussion.
+>
+> "See also [*1*] for more discussion" as you've already have
+> reference below.
+
+Thanks, mispasted E-Mail ID. Fixed.
+
+>>
+>> 1. https://public-inbox.org/git/871s8gd32p.fsf@evledraar.gmail.com/
+>>
+>> Signed-off-by: Ævar Arnfjörð Bjarmason <avarab@gmail.com>
+>> ---
+>>
+>> Here's a polished version of that. I think it makes sense to queue
+>> this up before any other refactoring of GETTEXT_POISON, and some patch
+>> to unconditionally preserve format specifiers as I suggested upthread
+>> could go on top of this.
+>> ...
+>> +int cmd_sh_i18n__helper(int argc, const char **argv, const char *prefix)
+>> +{
+>> +	int poison = -1;
+>> +	struct option options[] = {
+>> +		OPT_BOOL(0, "git-test-gettext-poison", &poison,
+>> +			 N_("is GIT_TEST_GETTEXT_POISON in effect?")),
+>> +		OPT_END()
+>> +	};
+>> +
+>> +	argc = parse_options(argc, argv, NULL, options,
+>> +			     builtin_sh_i18n_helper_usage, PARSE_OPT_KEEP_ARGV0);
+>> +
+>> +	if (poison != -1)
+>> +		return !git_env_bool("GIT_TEST_GETTEXT_POISON", 0);
+>
+> Hmm?  If "--[no-]git-test-gettext-poison" is given, poison is either
+> 0 or 1, and we return the value we read from the environment?  What
+> convoluted way to implement the option is that, or is there anything
+> subtle that I am not getting?
+>
+> If the "default" parameter to git_env_bool() were poison, and then
+> the option was renamed to "--get-git-text-gettext-poison", then I
+> sort of understand the code, though (it's like "git config" with
+> "--default" option).
+
+Yeah this didn't make much sense. The test helper is now gone, and the
+main helper doesn't use git_env_bool() but the utility function in
+gettext.h.
+
+> But if there is nothing subtle, it may make sense to implement this
+> as an opt-cmdmode instead.
+
+You mean something that works like "helper foo" instead of an option
+via "helper --foo"? Seemed easier just to use the opt parse mechanism.
+
+>> diff --git a/po/README b/po/README
+>> index fef4c0f0b5..dba46c4a40 100644
+>> --- a/po/README
+>> +++ b/po/README
+>> @@ -289,16 +289,11 @@ something in the test suite might still depend on the US English
+>>  version of the strings, e.g. to grep some error message or other
+>>  output.
+>>  
+>> -To smoke out issues like these Git can be compiled with gettext poison
+>> -support, at the top-level:
+>> +To smoke out issues like these Git tested with a translation mode that
+>> +emits gibberish on every call to gettext. To use it run the test suite
+>> +with it, e.g.:
+>
+> s/these Git tested/these, Git can be tested/; even though the comma
+> is not a new issue you introduced.
+
+Fixed. Range-diff of the whole thing below:
+
+1:  c93bf2f23f ! 1:  7bcb95a82d i18n: make GETTEXT_POISON a runtime option
+    @@ -24,19 +24,23 @@
+     
+         This allows for conditionally amending tests to test with/without
+         poison, similar to what 859fdc0c3c ("commit-graph: define
+    -    GIT_TEST_COMMIT_GRAPH", 2018-08-29) did for GIT_TEST_COMMIT_GRAPH, but
+    -    this patch doesn't change any of the existing tests to work like that.
+    +    GIT_TEST_COMMIT_GRAPH", 2018-08-29) did for GIT_TEST_COMMIT_GRAPH. Do
+    +    some of that, now we e.g. always run the t0205-gettext-poison.sh test.
+    +
+    +    I did enough there to remove the GETTEXT_POISON prerequisite, but its
+    +    inverse C_LOCALE_OUTPUT is still around, and surely some tests using
+    +    it can be converted to e.g. always set GIT_TEST_GETTEXT_POISON=false.
+     
+         Notes on the implementation:
+     
+    -     * The only reason we need a new "git-sh-i18n--helper" and the
+    -       corresponding "test-tool gettext-poison" is to expose
+    +     * The only reason we need a new "git-sh-i18n--helper" is to expose
+            git_env_bool() to shellscripts, since git-sh-i18n and friends need
+            to inspect the $GIT_TEST_GETTEXT_POISON variable.
+     
+    -       We only call these if $GIT_TEST_GETTEXT_POISON is set, or in the
+    -       test suite, and this code can go away for non-test code once the
+    -       last i18n-using shellscript is rewritten in C.
+    +       We only call it if $GIT_TEST_GETTEXT_POISON is set, or in the test
+    +       suite. This code can go away for non-test code once the last
+    +       i18n-using shellscript is rewritten in C, or if "git config" learns
+    +       to combine --bool and a value fed into it, see [2].
+     
+          * We still compile a dedicated GETTEXT_POISON build in Travis CI,
+            this is probably the wrong thing to do and should be followed-up
+    @@ -46,19 +50,40 @@
+     
+          * The reason for not doing:
+     
+    -           test_lazy_prereq GETTEXT_POISON 'test-tool gettext-poison'
+    -           test_lazy_prereq C_LOCALE_OUTPUT '! test-tool gettext-poison'
+    +           test_lazy_prereq C_LOCALE_OUTPUT [...]
+     
+    -       In test-lib.sh is because there's some interpolation problem with
+    +       in test-lib.sh is because there's some interpolation problem with
+            that syntax which makes t6040-tracking-info.sh fail. Hence using
+    -       the simpler test_set_prereq.
+    +       the simpler test_set_prereq. It'll fail with:
+    +
+    +           + git branch -vv
+    +           + sed -n -e
+    +           mkdir -p "$TRASH_DIRECTORY/prereq-test-dir" &&
+    +           (
+    +                   cd "$TRASH_DIRECTORY/prereq-test-dir" &&! git sh-i18n--helper --git-test-gettext-poison
+    +           )
+    +           sed: -e expression #1, char 2: unknown command: `m'
+    +           error: last command exited with $?=1
+    +           not ok 3 - branch -vv
+    +
+    +       This is some interpolation problem with how test_lazy_prereq works
+    +       that doesn't affect test_set_prereq.
+    +
+    +     * We now skip a test in t0000-basic.sh under
+    +       GIT_TEST_GETTEXT_POISON=true that wasn't skipped before. This test
+    +       relies on C locale output, but due to an edge case in how the
+    +       previous implementation of GETTEXT_POISON worked (reading it from
+    +       GIT-BUILD-OPTIONS) wasn't enabling poison correctly. Now it does,
+    +       and needs to be skipped.
+     
+         See also
+    -    https://public-inbox.org/git/871s8gd32p.fsf@evledraar.gmail.com/ for
+    +    https://public-inbox.org/git/878t2pd6yu.fsf@evledraar.gmail.com/ for
+         more discussion.
+     
+         1. https://public-inbox.org/git/871s8gd32p.fsf@evledraar.gmail.com/
+     
+    +    2. https://public-inbox.org/git/20181024074400.GA31239@sigill.intra.peff.net/
+    +
+         Signed-off-by: Ævar Arnfjörð Bjarmason <avarab@gmail.com>
+     
+      diff --git a/.gitignore b/.gitignore
+    @@ -101,14 +126,6 @@
+      # Define JSMIN to point to JavaScript minifier that functions as
+      # a filter to have gitweb.js minified.
+      #
+    -@@
+    - TEST_BUILTINS_OBJS += test-dump-untracked-cache.o
+    - TEST_BUILTINS_OBJS += test-example-decorate.o
+    - TEST_BUILTINS_OBJS += test-genrandom.o
+    -+TEST_BUILTINS_OBJS += test-gettext-poison.o
+    - TEST_BUILTINS_OBJS += test-hashmap.o
+    - TEST_BUILTINS_OBJS += test-index-version.o
+    - TEST_BUILTINS_OBJS += test-json-writer.o
+     @@
+      BUILTIN_OBJS += builtin/rm.o
+      BUILTIN_OBJS += builtin/send-pack.o
+    @@ -167,8 +184,9 @@
+     +{
+     +	int poison = -1;
+     +	struct option options[] = {
+    -+		OPT_BOOL(0, "git-test-gettext-poison", &poison,
+    -+			 N_("is GIT_TEST_GETTEXT_POISON in effect?")),
+    ++		OPT_BOOL_F(0, "git-test-gettext-poison", &poison,
+    ++			   N_("is GIT_TEST_GETTEXT_POISON in effect?"),
+    ++			   PARSE_OPT_NONEG),
+     +		OPT_END()
+     +	};
+     +
+    @@ -176,7 +194,7 @@
+     +			     builtin_sh_i18n_helper_usage, PARSE_OPT_KEEP_ARGV0);
+     +
+     +	if (poison != -1)
+    -+		return !git_env_bool("GIT_TEST_GETTEXT_POISON", 0);
+    ++		return !use_gettext_poison();
+     +
+     +	usage_with_options(builtin_sh_i18n_helper_usage, options);
+     +}
+    @@ -275,7 +293,7 @@
+      
+     -To smoke out issues like these Git can be compiled with gettext poison
+     -support, at the top-level:
+    -+To smoke out issues like these Git tested with a translation mode that
+    ++To smoke out issues like these, Git tested with a translation mode that
+     +emits gibberish on every call to gettext. To use it run the test suite
+     +with it, e.g.:
+      
+    @@ -308,44 +326,18 @@
+      test suite. Accept any boolean values that are accepted by git-config.
+      
+     
+    - diff --git a/t/helper/test-gettext-poison.c b/t/helper/test-gettext-poison.c
+    - new file mode 100644
+    - --- /dev/null
+    - +++ b/t/helper/test-gettext-poison.c
+    + diff --git a/t/lib-gettext.sh b/t/lib-gettext.sh
+    + --- a/t/lib-gettext.sh
+    + +++ b/t/lib-gettext.sh
+     @@
+    -+#include "test-tool.h"
+    -+#include "git-compat-util.h"
+    -+#include "thread-utils.h"
+    -+#include "gettext.h"
+    -+
+    -+int cmd__gettext_poison(int argc, const char **argv)
+    -+{
+    -+	return use_gettext_poison() ? 0 : 1;
+    -+}
+    -
+    - diff --git a/t/helper/test-tool.c b/t/helper/test-tool.c
+    - --- a/t/helper/test-tool.c
+    - +++ b/t/helper/test-tool.c
+    -@@
+    - 	{ "dump-untracked-cache", cmd__dump_untracked_cache },
+    - 	{ "example-decorate", cmd__example_decorate },
+    - 	{ "genrandom", cmd__genrandom },
+    -+	{ "gettext-poison", cmd__gettext_poison },
+    - 	{ "hashmap", cmd__hashmap },
+    - 	{ "index-version", cmd__index_version },
+    - 	{ "json-writer", cmd__json_writer },
+    -
+    - diff --git a/t/helper/test-tool.h b/t/helper/test-tool.h
+    - --- a/t/helper/test-tool.h
+    - +++ b/t/helper/test-tool.h
+    -@@
+    - int cmd__dump_untracked_cache(int argc, const char **argv);
+    - int cmd__example_decorate(int argc, const char **argv);
+    - int cmd__genrandom(int argc, const char **argv);
+    -+int cmd__gettext_poison(int argc, const char **argv);
+    - int cmd__hashmap(int argc, const char **argv);
+    - int cmd__index_version(int argc, const char **argv);
+    - int cmd__json_writer(int argc, const char **argv);
+    + 
+    + . "$GIT_BUILD_DIR"/git-sh-i18n
+    + 
+    +-if test_have_prereq GETTEXT && ! test_have_prereq GETTEXT_POISON
+    ++if test_have_prereq GETTEXT && test_have_prereq C_LOCALE_OUTPUT
+    + then
+    + 	# is_IS.UTF-8 on Solaris and FreeBSD, is_IS.utf8 on Debian
+    + 	is_IS_locale=$(locale -a 2>/dev/null |
+     
+      diff --git a/t/t0000-basic.sh b/t/t0000-basic.sh
+      --- a/t/t0000-basic.sh
+    @@ -360,6 +352,37 @@
+      		test-verbose "test verbose" --verbose <<-\EOF &&
+      	test_expect_success "passing test" true
+     
+    + diff --git a/t/t0205-gettext-poison.sh b/t/t0205-gettext-poison.sh
+    + --- a/t/t0205-gettext-poison.sh
+    + +++ b/t/t0205-gettext-poison.sh
+    +@@
+    + 
+    + test_description='Gettext Shell poison'
+    + 
+    ++GIT_TEST_GETTEXT_POISON=true
+    ++export GIT_TEST_GETTEXT_POISON
+    + . ./lib-gettext.sh
+    + 
+    +-test_expect_success GETTEXT_POISON 'sanity: $GIT_INTERNAL_GETTEXT_SH_SCHEME" is poison' '
+    ++test_expect_success 'sanity: $GIT_INTERNAL_GETTEXT_SH_SCHEME" is poison' '
+    +     test "$GIT_INTERNAL_GETTEXT_SH_SCHEME" = "poison"
+    + '
+    + 
+    +-test_expect_success GETTEXT_POISON 'gettext: our gettext() fallback has poison semantics' '
+    ++test_expect_success 'gettext: our gettext() fallback has poison semantics' '
+    +     printf "# GETTEXT POISON #" >expect &&
+    +     gettext "test" >actual &&
+    +     test_cmp expect actual &&
+    +@@
+    +     test_cmp expect actual
+    + '
+    + 
+    +-test_expect_success GETTEXT_POISON 'eval_gettext: our eval_gettext() fallback has poison semantics' '
+    ++test_expect_success 'eval_gettext: our eval_gettext() fallback has poison semantics' '
+    +     printf "# GETTEXT POISON #" >expect &&
+    +     eval_gettext "test" >actual &&
+    +     test_cmp expect actual &&
+    +
+      diff --git a/t/t3406-rebase-message.sh b/t/t3406-rebase-message.sh
+      --- a/t/t3406-rebase-message.sh
+      +++ b/t/t3406-rebase-message.sh
+    @@ -377,18 +400,33 @@
+      --- a/t/t7201-co.sh
+      +++ b/t/t7201-co.sh
+     @@
+    + test_expect_success 'checkout to detach HEAD' '
+    + 	git config advice.detachedHead true &&
+      	git checkout -f renamer && git clean -f &&
+    - 	git checkout renamer^ 2>messages &&
+    - 	test_i18ngrep "HEAD is now at 7329388" messages &&
+    +-	git checkout renamer^ 2>messages &&
+    +-	test_i18ngrep "HEAD is now at 7329388" messages &&
+     -	(test_line_count -gt 1 messages || test -n "$GETTEXT_POISON") &&
+    -+	(
+    -+		test_line_count -gt 1 messages ||
+    -+		test_have_prereq GETTEXT_POISON
+    -+	) &&
+    ++	GIT_TEST_GETTEXT_POISON=false git checkout renamer^ 2>messages &&
+    ++	grep "HEAD is now at 7329388" messages &&
+    ++	test_line_count -gt 1 messages &&
+      	H=$(git rev-parse --verify HEAD) &&
+      	M=$(git show-ref -s --verify refs/heads/master) &&
+      	test "z$H" = "z$M" &&
+     
+    + diff --git a/t/t9902-completion.sh b/t/t9902-completion.sh
+    + --- a/t/t9902-completion.sh
+    + +++ b/t/t9902-completion.sh
+    +@@
+    + 	verbose test -z "$__git_all_commands"
+    + '
+    + 
+    +-test_expect_success !GETTEXT_POISON 'sourcing the completion script clears cached merge strategies' '
+    ++test_expect_success 'sourcing the completion script clears cached merge strategies' '
+    ++	GIT_TEST_GETTEXT_POISON=false &&
+    + 	__git_compute_merge_strategies &&
+    + 	verbose test -n "$__git_merge_strategies" &&
+    + 	. "$GIT_BUILD_DIR/contrib/completion/git-completion.bash" &&
+    +
+      diff --git a/t/test-lib-functions.sh b/t/test-lib-functions.sh
+      --- a/t/test-lib-functions.sh
+      +++ b/t/test-lib-functions.sh
+    @@ -417,7 +455,7 @@
+      	fi
+      
+     -	if test -n "$GETTEXT_POISON"
+    -+	if ! test_have_prereq C_LOCALE_OUTPUT
+    ++	if test_have_prereq !C_LOCALE_OUTPUT
+      	then
+      		# pretend success
+      		return 0
+    @@ -438,8 +476,9 @@
+     -else
+     -	test_set_prereq C_LOCALE_OUTPUT
+     -fi
+    -+test-tool gettext-poison && test_set_prereq GETTEXT_POISON
+    -+test-tool gettext-poison || test_set_prereq C_LOCALE_OUTPUT
+    ++## Fails in the 'branch -vv' test in t6040-tracking-info.sh
+    ++#test_lazy_prereq C_LOCALE_OUTPUT '! git sh-i18n--helper --git-test-gettext-poison'
+    ++git sh-i18n--helper --git-test-gettext-poison || test_set_prereq C_LOCALE_OUTPUT
+      
+      if test -z "$GIT_TEST_CHECK_CACHE_TREE"
+      then
+
  .gitignore                |  1 +
  .travis.yml               |  2 +-
  Makefile                  | 10 +---------
